# Generated by Django 3.2.25 on 2026-05-14 19:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20260514_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='publish',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
