# Generated by Django 3.2.25 on 2026-05-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_articles_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='publish',
            field=models.DateField(blank=True, null=True),
        ),
    ]
